### PR TITLE
Fixes Issue 67 - Add User's Orders History to Firestore

### LINKED ISSUE #67: Add User's Orders History to Firestore
Send the payment status from Stripe to front-end (Main.js) - handle different statuses (400, etc).

If payment status was successful, send fetch request from front-end to userRoutes to create an Order Collection (this will need to have the userID).

Once fetch request above is made, we will now have the orderID. We can then use this orderID to create another fetch request to the backend userRoutes.js file to post the ordered Items to the right orderID history.

Steps: 
Write backend routes: 
- [x] post to firebase to create order per user
- [x]  post to firebase to add items to the rider orderID

### PR DESCRIPTION
**Pull request by nilan01**
Closes #67

This PR adds the ability to store the user's order to an order history collection on Firestore.

The User who creates the order will either have a new order array being added to the `orders` subcollection (located on their user document, or a new subcollection will be created if a user does not have one.

@chrispinkney has also changed the way that users are stored in the database. We are using [hasha](https://www.npmjs.com/package/hasha/
). We are using hasha in order to also be able to implement Apple strategy using Passport.js

We are currently storing a user order with a unique id generated by firestore.

### CODE REVIEW

**Review by chrispinkney — APPROVED** [review]

File: src/backend/services/passport.js [hunk 1]
```diff
@@ -24,7 +24,8 @@ passport.use(
     },
     (accessToken, refreshToken, profile, done) => {
       const data = {
-        id: profile.id,
+        // id: profile.id,
```
Comment (pyvelkov) [inline src/backend/services/passport.js:27]: delete comment

Comment (nilan01) [reply src/backend/services/passport.js]: @pyvelkov good catch, removed!

**Review by pyvelkov — APPROVED** [review]
